apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    io.kompose.service: notification-service  # Remove extra colon
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP