apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    io.kompose.service: phpmyadmin
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081  # phpMyAdmin en http://<minikube-ip>:30081
