apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\PERSONAL\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
    traefik.enable: "true"
    traefik.http.routers.user-service.rule: Host(`127.0.0.1`)
    traefik.http.services.user-service.loadbalancer.server.port: "8000"
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\PERSONAL\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
        traefik.enable: "true"
        traefik.http.routers.user-service.rule: Host(`127.0.0.1`)
        traefik.http.services.user-service.loadbalancer.server.port: "8000"
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ADVERTISED_LISTENERS
                  name: env
            - name: KAFKA_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_URL
                  name: env
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_LISTENERS
                  name: env
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_TOPIC
                  name: env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: env
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_HOST
                  name: env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: env
            - name: PROMETHEUS_PORT
              valueFrom:
                configMapKeyRef:
                  key: PROMETHEUS_PORT
                  name: env
          image: oscarrosero/microservices-user-service
          ports:
            - containerPort: 8000
          name: user-service
      hostname: user-service
      restartPolicy: Always